// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIym3ECWU7z-JRPazH25dnkykqMK7_NfY',
    appId: '1:1067437829910:web:6d657b5d46f2dd78952a37',
    messagingSenderId: '1067437829910',
    projectId: 'note-app-a9171',
    authDomain: 'note-app-a9171.firebaseapp.com',
    storageBucket: 'note-app-a9171.firebasestorage.app',
    measurementId: 'G-XBWFQF7ST8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5utT18qx5rEWQwPhSJCnvw81zw3_TADE',
    appId: '1:1067437829910:android:24271f0216925331952a37',
    messagingSenderId: '1067437829910',
    projectId: 'note-app-a9171',
    storageBucket: 'note-app-a9171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzB35X7aHX5fdxxmTeNQoCC9YR3xFrVI',
    appId: '1:1067437829910:ios:1651bd56e29000e5952a37',
    messagingSenderId: '1067437829910',
    projectId: 'note-app-a9171',
    storageBucket: 'note-app-a9171.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

}